# Site settings
title: Robert Herbig
description: >
  I try to improve myself and those around me every day.
baseurl: ""
url: "https://www.rpherbig.com"
# Used by jekyll-seo-tag for Twitter card meta tags. Keep in sync with theme.yml social.twitter
twitter_username: RobertHerbig

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
