# Site settings
title: Robert Herbig
email: Robert.P.Herbig@gmail.com
description: >
  I try to improve myself and those around me every day.
baseurl: ""
url: "https://www.rpherbig.com"
twitter_username: RobertHerbig
github_username:  rpherbig

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
